export const LoginTypes = {
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
    USER_LOADED : 'USER_LOADED',
    GET_PHOTOS: 'GET_PHOTOS',
    ADD_PHOTOS: 'ADD_PHOTOS',
    DEL_PHOTOS: 'DEL_PHOTOS',
    GET_ERRORS: 'GET_ERRORS'
}